test

diff --git a/scripts/bump-plugin b/scripts/bump-plugin
--- a/scripts/bump-plugin
+++ b/scripts/bump-plugin
@@ -18,20 +18,18 @@ set -eux -o pipefail
 
 bumpversion="python -m bumpversion"
 
-# if $bumpversion > /dev/null != 2; then
-#   echo "bump2version must be installed to bump versions; install using 'pip install bump2version'"
-#   exit 1
-# fi
+if $bumpversion > /dev/null != 2; then
+  echo "bump2version must be installed to bump versions; install using 'pip install bump2version'"
+  exit 1
+fi
 
-# branch=$(git branch --show-current)
-# if [ "$branch" != "main" ]; then
-#     echo "Error: can only release a new version from main branch"
-#     exit 1
-# fi
+branch=$(git branch --show-current)
+if [ "$branch" != "main" ]; then
+    echo "Error: can only release a new version from main branch"
+    exit 1
+fi
 
 part="$1"
-
-echo $part
 
 # cd plugin
 CURRENT_VERSION=$($bumpversion --dry-run --list $part --allow-dirty | grep "^current_version" | sed -r s,"^.*=",,)
@@ -39,18 +37,3 @@ NEW_VERSION=$($bumpversion --dry-run --list $part --allow-dirty | grep -E "^new_
 BRANCH="release/v$NEW_VERSION"
 git checkout -b "$BRANCH"
 $bumpversion $part
-
-set +x
-
-git push -u origin $BRANCH
-echo "Bumped version of plugin from $CURRENT_VERSION to $NEW_VERSION."
-echo
-if command -v gh > /dev/null; then
-  gh pr create --fill
-  echo "A pull request has been created. After merging, pull and run ./scripts/release-plugin to release."
-else
-  echo "Create a new pull request at:"
-  echo
-  echo "    https://github.com/fcjack/ga-test/pull/new/$BRANCH"
-fi
-echo
